version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"

  [analyzers.meta]


[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.7"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",

    "angular"
  ]
  environment = [
    "nodejs",
    "browser",

    "vitest"
  ]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/KOSASIH/pi-explorer"

[[analyzers]]
name = "docker"

  [analyzers.meta]


[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "clang-format"

[[transformers]]


